const state={tab:"market",updated:new Date()};
const indices=[
 ["NIFTY 50","NIFTY","+0.0%","+0.0%","Index"],
 ["BANK NIFTY","BANKNIFTY","+0.0%","+0.0%","Index"],
 ["SENSEX","SENSEX","+0.0%","+0.0%","Index"],
 ["MIDCAP NIFTY","MIDCPNIFTY","+0.0%","+0.0%","Index"]
];
const watch=[
["RELIANCE","Energy",8.4,91,82,88],["HDFCBANK","Banking",7.8,89,79,84],["ICICIBANK","Banking",7.5,87,81,82],
["SBIN","Banking",7.2,86,77,80],["AXISBANK","Banking",6.9,84,76,78],["BHARTIARTL","Telecom",6.7,83,80,77],
["INFY","IT",6.4,81,74,74],["TCS","IT",6.1,79,72,71],["LT","Capital Goods",5.8,78,76,70],
["ITC","FMCG",5.4,77,73,69],["TATAMOTORS","Auto",-6.8,88,67,83],["ADANIENT","Diversified",-6.4,86,71,81],
["JSWENERGY","Power",-6.0,84,69,79],["MARUTI","Auto",-5.6,82,72,76],["BAJFINANCE","Finance",-5.2,80,70,74],
["SUNPHARMA","Pharma",4.9,76,78,68],["HINDALCO","Metals",-4.7,75,68,71],["COALINDIA","Mining",-4.4,73,71,67],
["ONGC","Oil & Gas",-4.1,72,69,65],["TATASTEEL","Metals",-3.8,70,66,63],["M&M","Auto",3.7,69,77,61],
["WIPRO","IT",3.4,68,70,59],["NTPC","Power",3.1,67,73,57],["POWERGRID","Power",2.8,65,75,55],
["HDFCLIFE","Insurance",-2.6,64,62,53]
];
function shell(){return `<header class="top"><div class="brand"><div><b>TRAP AI</b><br><small>Market Intelligence Engine</small><div class="status">● MARKET WATCH · LIVE FEED SLOT READY</div></div><button class="action" onclick="refresh()">Refresh</button></div><nav class="nav">${["market","scanner","options","traps","backtest"].map(x=>`<button class="${state.tab===x?"active":""}" onclick="go('${x}')">${x==="market"?"MARKET WATCH":x==="scanner"?"TOP 25 F&O":x==="options"?"OPTIONS":x==="traps"?"TOP 3 FADE":"BACKTEST"}</button>`).join("")}</nav></header><main class="main"><div id="content"></div><div class="footer">TRAP AI research engine. Live data, options-chain and news feeds must be connected before any displayed score is treated as real-time.</div></main>`} 
function indexCards(){return `<div class="grid">${indices.map(x=>`<div class="card metric"><span>${x[0]}</span><strong>—</strong><span>${x[1]} · awaiting live feed</span></div>`).join("")}</div>`}
function market(){return `<div class="hero"><section class="card"><div class="label">Market Watch</div><div class="score bull">—</div><span class="pill">AWAITING LIVE DATA</span><p style="color:var(--muted);line-height:1.5">The live engine will calculate sentiment from global markets, news, macro, FII/DII, futures, options positioning, technical structure and crowding.</p><div class="notice"><b>FADE LOGIC</b><br>High crowding alone is never a short/long trigger. TRAP AI requires crowding + divergence + technical confirmation + catalyst/regime checks.</div></section><section class="card"><div class="label">Decision pipeline</div><h2>Top 3 Opposite Trades</h2><p style="color:var(--muted)">From the Top 25 F&O universe, rank candidates by crowding, trap score, divergence and reversal confirmation.</p><button class="action" onclick="go('traps')">Open Top 3</button></section></div>${indexCards()}<section class="section"><h2>Index Market Watch</h2><div class="rows">${indices.map(x=>`<div class="row"><b>${x[0]}</b><span>Sentiment —</span><span>Crowding —</span><span class="right">Status: feed pending</span></div>`).join("")}</div></section>`}
function scanner(){return `<section class="card"><div class="signal"><div><div class="label">Universe</div><h2>Top 25 F&O Market Watch</h2></div><span class="pill">25 STOCKS</span></div><p class="notice">Scores below are UI test values only. Once the backend is connected, every value will be calculated from timestamped market data.</p><div class="rows">${watch.map((s,i)=>`<div class="row"><b>${i+1}. ${s[0]}<br><small style="color:var(--muted)">${s[1]}</small></b><span class="${s[2]<0?"bear":"bull"}">${s[2]>0?"+":""}${s[2]}</span><span>CR ${s[3]}</span><span class="right">Trap ${s[5]}</span></div>`).join("")}</div></section>`}
function options(){return `<section class="card"><div class="label">Option engine</div><h2>Best asymmetric opportunities</h2><div class="rows">${[["NIFTY","Direction pending","OOS —"],["BANKNIFTY","Direction pending","OOS —"],["Top F&O stock","Direction pending","OOS —"]].map(x=>`<div class="row"><b>${x[0]}</b><span>${x[1]}</span><span>${x[2]}</span><span class="right">No live trade</span></div>`).join("")}</div><p class="notice">The engine will choose the underlying first, then evaluate strike, delta, IV, gamma, theta, vega, liquidity, spread and expiry. A 3×–4× outcome is an opportunity target, not a guarantee.</p></section>`}
function traps(){const top=[...watch].sort((a,b)=>b[3]+b[5]-a[3]-a[5]).slice(0,3);return `<section class="card"><div class="label">Opposite-trade shortlist</div><h2>Top 3 highest crowding + trap candidates</h2><p class="notice">These are <b>candidate fades</b>, not automatic trades. The live version will require at least two independent reversal confirmations and a false-contrarian filter.</p><div class="rows">${top.map((s,i)=>`<div class="card"><div class="signal"><b>#${i+1} ${s[0]}</b><span class="pill">Crowding ${s[3]}</span></div><p style="color:var(--muted)">Sentiment ${s[2]>0?"+":""}${s[2]} · Technical ${s[4]} · Trap ${s[5]}</p><div class="bar"><i style="width:${s[3]}%"></i></div><p style="font-size:12px;color:var(--muted)">Required: divergence → structure break → confirmation → option selection</p></div>`).join("")}</div></section>`}
function backtest(){return `<section class="card"><div class="label">Historical replay</div><h2>Fade Strategy Validation</h2><p style="color:var(--muted)">Backtest the exact rule used by Top 3: crowding threshold + sentiment extreme + divergence + technical confirmation + catalyst/regime filter. No look-ahead data is allowed.</p><div class="grid">${["2007–2009","2016–2018","2020–2022","2024–2026"].map(x=>`<div class="card metric"><span>${x}</span><strong>—</strong><span>Awaiting historical feed</span></div>`).join("")}</div></section>`}
function render(){document.getElementById("app").innerHTML=shell();document.getElementById("content").innerHTML=({market,scanner,options,traps,backtest}[state.tab])()}
function go(t){state.tab=t;render()} function refresh(){state.updated=new Date();render()} render();